schemas:
  bootstrap: 8000
  dsets_custom: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://192.168.99.100:3090/themes/contrib/bootstrap/favicon.ico'
  use_default: 0
features:
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 0
  node_user_picture: 0
logo:
  path: ''
  url: ''
  use_default: 0
table_responsive: '-1'
table: ''
