sids: {  }
authenticationMode: 1
loginUIUsernameTxt: ''
loginUIPasswordTxt: ''
ldapUserHelpLinkUrl: ''
ldapUserHelpLinkText: ''
emailOption: 3
emailUpdate: 1
emailTemplateHandling: none
emailTemplate: '@username@example.com'
emailTemplateUsageResolveConflict: false
emailTemplateUsageNeverUpdate: false
emailTemplateUsagePromptUser: false
emailTemplateUsageRedirectOnLogin: false
emailTemplateUsagePromptRegex: '.*@example\\.com'
passwordOption: 3
allowOnlyIfTextInDn: {  }
excludeIfTextInDn: {  }
excludeIfNoAuthorizations: null
ssoRemoteUserStripDomainName: null
ssoExcludedPaths: {  }
ssoExcludedHosts: {  }
seamlessLogin: null
ldapImplementation: null
cookieExpire: null
_core:
  default_config_hash: PhCAjUcRcM1gIsD2-W5N_sL91XOsCizjWcvXexo8lpA
