sids:
  lib_ldap: lib_ldap
authenticationMode: 1
loginUIUsernameTxt: 'Enter your UNB login ID'
loginUIPasswordTxt: ''
ldapUserHelpLinkUrl: ''
ldapUserHelpLinkText: ''
emailOption: 4
emailUpdate: 1
emailTemplateHandling: if_empty
emailTemplate: '@username@example.com'
emailTemplateUsageResolveConflict: false
emailTemplateUsageNeverUpdate: false
emailTemplateUsagePromptUser: false
emailTemplateUsageRedirectOnLogin: false
emailTemplateUsagePromptRegex: '.*@example\\.com'
passwordOption: 3
allowOnlyIfTextInDn: {  }
excludeIfTextInDn: {  }
excludeIfNoAuthorizations: 0
ssoRemoteUserStripDomainName: null
ssoExcludedPaths: {  }
ssoExcludedHosts: {  }
seamlessLogin: null
ldapImplementation: null
cookieExpire: null
_core:
  default_config_hash: PhCAjUcRcM1gIsD2-W5N_sL91XOsCizjWcvXexo8lpA
