favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://192.168.99.100:3090/themes/contrib/bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: false
  comment_user_verification: false
  favicon: true
  node_user_picture: false
logo:
  path: ''
  url: ''
  use_default: false
schemas:
  bootstrap: 8000
  unb_lib_theme: 8000
table: ''
